import assert from 'node:assert/strict';
import fs from 'node:fs';

const indexSource = fs.readFileSync(new URL('../index.js', import.meta.url), 'utf8');
const compatSource = fs.readFileSync(new URL('../st-compat.js', import.meta.url), 'utf8');
const styleSource = fs.readFileSync(new URL('../style.css', import.meta.url), 'utf8');
const manifest = JSON.parse(fs.readFileSync(new URL('../manifest.json', import.meta.url), 'utf8'));

const ids = [...indexSource.matchAll(/\bid="([^"]+)"/g)].map(match => match[1]);
const duplicateIds = ids.filter((id, index) => ids.indexOf(id) !== index);
assert.deepEqual(duplicateIds, [], 'Static UI contains duplicate IDs');

const staticIdSet = new Set(ids);
const queriedIds = [
    ...indexSource.matchAll(/querySelector\(['"]#([A-Za-z0-9_-]+)['"]\)/g),
].map(match => match[1]);
const dynamicIds = new Set(['pf-overlay', 'pf-settings', 'pf-fab', 'extensions_settings2', 'extensions_settings', 'amount_gen']);
const missingIds = [...new Set(queriedIds)].filter(id => !staticIdSet.has(id) && !dynamicIds.has(id));
assert.deepEqual(missingIds, [], 'A queried UI ID is missing from the static template');

const version = indexSource.match(/const VERSION = '([^']+)'/)?.[1];
assert.equal(version, manifest.version, 'Manifest and runtime versions must match');
assert.equal(manifest.minimum_client_version, '1.14.0');
assert.match(indexSource, /initializeHostCompatibility/);
assert.match(indexSource, /buildLegacyChatStreamingPayload/);
assert.match(indexSource, /buildLegacyTextStreamingPayload/);
assert.match(indexSource, /detectHostCapabilities/);
assert.match(indexSource, /generateRawCompat/);
assert.match(indexSource, /readOpeningGreetingCompat/);
assert.match(indexSource, /subscribeHostEvents/);
assert.match(indexSource, /旧版酒馆兼容模式已启用/);
assert.match(indexSource, /buildPersonaSystemPrompt\(\)/);
assert.match(indexSource, /buildPersonaRefinementPrompt/);
assert.match(indexSource, /buildPersonaRefinementSystemPrompt/);
assert.match(indexSource, /getCurrentPersonaContext/);
assert.match(indexSource, /powerUserSettings/);
assert.match(indexSource, /persona_description/);
assert.match(indexSource, /data-mode="refine"/);
assert.match(indexSource, /pf-refine-note/);
assert.match(indexSource, /currentPersonaText/);
assert.match(indexSource, /customSectionPresets/);
assert.match(indexSource, /normalizeCustomSectionPresets/);
assert.match(indexSource, /saveCustomSectionPreset/);
assert.match(indexSource, /applyCustomSectionPreset/);
assert.match(indexSource, /deleteCustomSectionPreset/);
assert.match(indexSource, /pf-custom-preset-name/);
assert.match(indexSource, /pf-fab-size/);
assert.match(indexSource, /pf-reset-fab-size/);
assert.match(indexSource, /pf-upload-icon/);
assert.match(indexSource, /pf-reset-icon/);
assert.match(indexSource, /floatingSize/);
assert.match(indexSource, /floatingIcon/);
assert.match(styleSource, /--pf-fab-size/);
assert.match(indexSource, /pf-custom-preset-select/);
assert.match(indexSource, /Object\.assign\(current, migrated\)/);
assert.match(indexSource, /const sectionIds = getSelectedSections\(getCurrentSectionSelection\(\)\)/);
assert.doesNotMatch(indexSource, /root\[SETTINGS_KEY\] = migrated/);
assert.match(indexSource, /renderStructuredResult\(/);
assert.match(indexSource, /personaWorldNames/);
assert.match(indexSource, /pf-length-preset/);
assert.match(indexSource, /pf-target-length/);
assert.match(indexSource, /customTargetLength/);
assert.match(indexSource, /normalizeLengthPreset/);
assert.match(indexSource, /pf-reference-greeting/);
assert.match(indexSource, /referenceGreeting/);
assert.match(indexSource, /first_mes/);
assert.match(compatSource, /ctx\?\.chat\) \? ctx\.chat\[0\]/);
assert.match(indexSource, /getOpeningGreetingReference/);
assert.match(indexSource, /collectOpeningGreeting/);
assert.match(indexSource, /pf-refinement-view-toolbar/);
assert.match(indexSource, /pf-comparison/);
assert.match(indexSource, /renderRefinementComparison/);
assert.match(indexSource, /buildLocalTextDiff/);
assert.match(indexSource, /data-result-view="comparison"/);
assert.match(indexSource, /pf-content-jump/);
assert.match(indexSource, /resolveTargetLength/);
assert.match(indexSource, /floatingPosition/);
assert.match(indexSource, /bindFloatingDrag/);
assert.match(indexSource, /isPhoneViewport/);
assert.match(indexSource, /pf-open-button/);
assert.match(indexSource, /syncTargetLengthControl/);
assert.match(indexSource, /streamOutput/);
assert.match(indexSource, /generateRawWithStreaming/);
assert.match(indexSource, /getCurrentApiStreaming/);
assert.match(indexSource, /getActiveModelInfo/);
assert.match(indexSource, /readSelectedConnectionProfile/);
assert.match(indexSource, /generateWithCurrentConnection/);
assert.match(indexSource, /getResponseTokenBudget/);
assert.match(compatSource, /generateRawDataCompat/);
assert.match(compatSource, /extractGeneratedTextCompat/);
assert.match(indexSource, /ChatCompletionService/);
assert.match(indexSource, /TextCompletionService/);
assert.match(indexSource, /presetToGeneratePayload/);
assert.match(indexSource, /mainApi === 'openai'/);
assert.match(indexSource, /mainApi === 'textgenerationwebui'/);
assert.match(indexSource, /updateCount > 1/);
assert.match(indexSource, /scrollStreamingResultIntoView/);
assert.match(indexSource, /setStreamingFallbackPreview/);
assert.match(indexSource, /const currentApi = connection \? null : getCurrentApiStreaming\(liveContext\)/);
assert.match(indexSource, /CONNECTION_PROFILE_LOADED/);
assert.match(indexSource, /Target Chinese character count is a writing instruction, not an API token limit/);
assert.match(indexSource, /createGenerationParameters\(settings, model, 'normal', messages\)/);
assert.match(indexSource, /CHAT_COMPLETION_SETTINGS_READY/);
assert.match(indexSource, /TEXT_COMPLETION_SETTINGS_READY/);
assert.match(indexSource, /throw new Error\(`\$\{source\} · \$\{detail\}`\)/);
assert.doesNotMatch(indexSource, /renderCurrentResultProgressively/);

console.log('index wiring ok');
